"""Static word and phrase banks for the daily lesson."""

WORDS = [
    {"term": "meticulous", "meaning": "very careful and precise", "example": "She is meticulous about checking every detail before sending an email."},
    {"term": "reluctant", "meaning": "not eager and a little unwilling", "example": "He was reluctant to speak in front of the whole team."},
    {"term": "thrive", "meaning": "to grow strongly or do very well", "example": "Some people thrive in fast-paced environments."},
    {"term": "candid", "meaning": "honest and direct", "example": "I appreciate your candid feedback on my presentation."},
    {"term": "resilient", "meaning": "able to recover quickly after difficulty", "example": "Kids can be surprisingly resilient after big changes."},
    {"term": "frugal", "meaning": "careful about spending money", "example": "They are frugal, but they still travel a lot."},
    {"term": "diligent", "meaning": "hardworking and careful", "example": "She made steady progress because she was diligent every day."},
    {"term": "vague", "meaning": "not clear or specific", "example": "His instructions were too vague for the new intern."},
    {"term": "subtle", "meaning": "not obvious and hard to notice", "example": "There was a subtle change in her tone."},
    {"term": "feasible", "meaning": "possible and practical", "example": "The plan sounds good, but we need to check if it is feasible."},
    {"term": "hesitate", "meaning": "to pause because you are unsure", "example": "Do not hesitate to ask questions during the meeting."},
    {"term": "adapt", "meaning": "to change to fit a new situation", "example": "It takes time to adapt to a new city."},
    {"term": "insight", "meaning": "a clear and useful understanding", "example": "Her comment gave me real insight into the problem."},
    {"term": "scarce", "meaning": "hard to find or not enough", "example": "Free parking is scarce in that neighborhood."},
    {"term": "bold", "meaning": "confident and willing to take risks", "example": "It was a bold move to change careers at 40."},
    {"term": "convey", "meaning": "to communicate or make an idea known", "example": "The chart helps convey the main trend quickly."},
    {"term": "awkward", "meaning": "uncomfortable or embarrassing", "example": "There was an awkward silence after the joke failed."},
    {"term": "prompt", "meaning": "done quickly and without delay", "example": "Thank you for your prompt reply."},
    {"term": "sturdy", "meaning": "strong and not easily damaged", "example": "This table is simple, but it is very sturdy."},
    {"term": "generous", "meaning": "willing to give more than expected", "example": "That was a generous offer from your manager."},
    {"term": "crucial", "meaning": "extremely important", "example": "Clear communication is crucial in remote teams."},
    {"term": "eager", "meaning": "very interested and excited to do something", "example": "The students were eager to hear the results."},
    {"term": "brief", "meaning": "short in time or length", "example": "Let us keep the update brief and focused."},
    {"term": "flexible", "meaning": "able to change easily", "example": "A flexible schedule helps parents a lot."},
    {"term": "overlook", "meaning": "to fail to notice something", "example": "It is easy to overlook a small typo."},
    {"term": "clarify", "meaning": "to make something easier to understand", "example": "Could you clarify what you mean by urgent?"},
    {"term": "steady", "meaning": "regular and not changing suddenly", "example": "He made steady improvement over three months."},
    {"term": "convince", "meaning": "to make someone believe or agree", "example": "The data helped convince the team to try it."},
    {"term": "notion", "meaning": "an idea or belief", "example": "She rejected the notion that success must be fast."},
    {"term": "sincere", "meaning": "honest and genuine", "example": "His apology sounded sincere."},
]

PHRASES = [
    {"term": "hit the books", "meaning": "to study seriously", "example": "I need to hit the books this weekend before the exam."},
    {"term": "rain check", "meaning": "to postpone a plan until later", "example": "I am too tired tonight. Can I take a rain check?"},
    {"term": "spill the beans", "meaning": "to reveal a secret", "example": "Come on, spill the beans. What did they say?"},
    {"term": "under the weather", "meaning": "feeling slightly sick", "example": "I am a little under the weather today, so I will stay in."},
    {"term": "pull an all-nighter", "meaning": "to stay awake all night working or studying", "example": "He pulled an all-nighter to finish the project."},
    {"term": "cut to the chase", "meaning": "to get to the main point quickly", "example": "Let me cut to the chase and tell you the decision."},
    {"term": "hang out", "meaning": "to spend time relaxing with someone", "example": "We hung out downtown after work."},
    {"term": "give me a heads-up", "meaning": "to warn or inform someone in advance", "example": "Give me a heads-up if you will be late."},
    {"term": "on the same page", "meaning": "sharing the same understanding", "example": "Let us make sure we are on the same page before we start."},
    {"term": "a long shot", "meaning": "something unlikely to succeed", "example": "Getting tickets now is a long shot."},
    {"term": "no big deal", "meaning": "not important or not a problem", "example": "Thanks for helping. No big deal, happy to do it."},
    {"term": "cut corners", "meaning": "to do something cheaply or carelessly", "example": "They saved money by cutting corners, and the quality dropped."},
    {"term": "crash", "meaning": "to sleep or stay somewhere temporarily", "example": "Can I crash on your couch after the concert?"},
    {"term": "flake out", "meaning": "to cancel plans or not follow through", "example": "Do not flake out on me at the last minute."},
    {"term": "wrap my head around", "meaning": "to understand something complicated", "example": "I am still trying to wrap my head around the new tax rules."},
    {"term": "rip off", "meaning": "to charge too much or cheat someone", "example": "That tourist trap restaurant is a total rip off."},
    {"term": "bail", "meaning": "to leave suddenly or cancel", "example": "He bailed on dinner because he was exhausted."},
    {"term": "go with the flow", "meaning": "to stay relaxed and accept changes", "example": "We do not have a full plan, so let us just go with the flow."},
    {"term": "shoot me a text", "meaning": "to send me a text message", "example": "Shoot me a text when you get home."},
    {"term": "in hot water", "meaning": "in trouble", "example": "He is in hot water with his boss after missing the deadline."},
    {"term": "call it a day", "meaning": "to stop working for now", "example": "We have done enough. Let us call it a day."},
    {"term": "back me up", "meaning": "to support what I say", "example": "Can you back me up in the meeting if this comes up?"},
    {"term": "my bad", "meaning": "it was my mistake", "example": "My bad, I sent the wrong file."},
    {"term": "the ball is in your court", "meaning": "it is your turn to act or decide", "example": "I sent the proposal yesterday, so now the ball is in your court."},
    {"term": "beat around the bush", "meaning": "to avoid saying something directly", "example": "Do not beat around the bush. Just tell me what happened."},
    {"term": "pull yourself together", "meaning": "to calm down and regain control", "example": "Take a breath and pull yourself together before the interview."},
    {"term": "fired up", "meaning": "excited and full of energy", "example": "The team was fired up after the coach's speech."},
    {"term": "down to earth", "meaning": "practical and easy to relate to", "example": "Even though she is famous, she is very down to earth."},
    {"term": "throw me a bone", "meaning": "to give a small favor or helpful sign", "example": "Throw me a bone and tell me whether I am close."},
    {"term": "take a pass", "meaning": "to decide not to join or accept", "example": "I am going to take a pass on dessert tonight."},
]
