"""Static word and phrase banks for the daily lesson."""

WORDS = [
    {"term": "ubiquitous", "meaning": "present or found everywhere", "example": "Smartphones are now so ubiquitous that many services assume you have one."},
    {"term": "pragmatic", "meaning": "focused on practical results rather than theory", "example": "She took a pragmatic approach and fixed the simplest issue first."},
    {"term": "convoluted", "meaning": "complicated and difficult to follow", "example": "The explanation was so convoluted that everyone left more confused."},
    {"term": "tenuous", "meaning": "weak, uncertain, or not strongly supported", "example": "The link between the two events felt tenuous at best."},
    {"term": "astute", "meaning": "quick to notice and understand things clearly", "example": "His astute question exposed the biggest weakness in the plan."},
    {"term": "coherent", "meaning": "clear, logical, and consistent", "example": "Her argument was concise and surprisingly coherent for such a messy topic."},
    {"term": "ambivalent", "meaning": "having mixed feelings about something", "example": "I felt ambivalent about the promotion because it meant moving away."},
    {"term": "cursory", "meaning": "done quickly and without much attention", "example": "They gave the contract only a cursory review before signing it."},
    {"term": "lucid", "meaning": "very clear and easy to understand", "example": "The professor gave a lucid explanation of a difficult concept."},
    {"term": "succinct", "meaning": "brief but clear and meaningful", "example": "His summary was succinct but still captured the main risks."},
    {"term": "adamant", "meaning": "firm and unwilling to change your mind", "example": "She was adamant that the launch should be delayed."},
    {"term": "nuanced", "meaning": "showing subtle details or distinctions", "example": "The best answer was more nuanced than a simple yes or no."},
    {"term": "sporadic", "meaning": "happening at irregular times and not often", "example": "We had sporadic internet issues throughout the afternoon."},
    {"term": "impeccable", "meaning": "perfect and without faults", "example": "Her timing during the presentation was impeccable."},
    {"term": "wary", "meaning": "careful because you think there may be danger or trouble", "example": "Investors are still wary of companies with unclear cash flow."},
    {"term": "eloquent", "meaning": "fluent, clear, and persuasive in speaking or writing", "example": "He gave an eloquent defense of public education."},
    {"term": "volatile", "meaning": "likely to change suddenly or become unstable", "example": "Oil prices remain volatile after the policy announcement."},
    {"term": "obsolete", "meaning": "no longer useful because something newer exists", "example": "That file format is basically obsolete now."},
    {"term": "plausible", "meaning": "seeming reasonable or likely to be true", "example": "At first, his excuse sounded plausible."},
    {"term": "arbitrary", "meaning": "based on random choice instead of a clear reason", "example": "The deadline felt arbitrary because no one explained it."},
    {"term": "methodical", "meaning": "done in a careful, ordered way", "example": "Her methodical note-taking made the audit much easier."},
    {"term": "vindicate", "meaning": "to prove that someone or something was right", "example": "The final results vindicated their early decision to stay patient."},
    {"term": "scrutinize", "meaning": "to examine something very carefully", "example": "Analysts will scrutinize every line of the earnings report."},
    {"term": "mitigate", "meaning": "to reduce the bad effects of something", "example": "We added extra checks to mitigate the risk of bad data."},
    {"term": "daunting", "meaning": "making you feel intimidated because it seems difficult", "example": "Learning legal English can feel daunting at first."},
    {"term": "pervasive", "meaning": "spread widely throughout something", "example": "There was a pervasive sense of uncertainty across the industry."},
    {"term": "candidly", "meaning": "in an honest and direct way", "example": "Candidly, I do not think the current timeline is realistic."},
    {"term": "discrepancy", "meaning": "a difference between things that should match", "example": "We found a discrepancy between the invoice and the shipment total."},
    {"term": "implicit", "meaning": "suggested or understood without being directly stated", "example": "There was an implicit expectation that everyone would work late."},
    {"term": "fortify", "meaning": "to strengthen or make more secure", "example": "The company moved to fortify its balance sheet before expanding."},
]

PHRASES = [
    {"term": "hit the books", "meaning": "to study seriously", "example": "I need to hit the books this weekend before the exam."},
    {"term": "rain check", "meaning": "to postpone a plan until later", "example": "I am too tired tonight. Can I take a rain check?"},
    {"term": "spill the beans", "meaning": "to reveal a secret", "example": "Come on, spill the beans. What did they say?"},
    {"term": "under the weather", "meaning": "feeling slightly sick", "example": "I am a little under the weather today, so I will stay in."},
    {"term": "pull an all-nighter", "meaning": "to stay awake all night working or studying", "example": "He pulled an all-nighter to finish the project."},
    {"term": "cut to the chase", "meaning": "to get to the main point quickly", "example": "Let me cut to the chase and tell you the decision."},
    {"term": "hang out", "meaning": "to spend time relaxing with someone", "example": "We hung out downtown after work."},
    {"term": "give me a heads-up", "meaning": "to warn or inform someone in advance", "example": "Give me a heads-up if you will be late."},
    {"term": "on the same page", "meaning": "sharing the same understanding", "example": "Let us make sure we are on the same page before we start."},
    {"term": "a long shot", "meaning": "something unlikely to succeed", "example": "Getting tickets now is a long shot."},
    {"term": "no big deal", "meaning": "not important or not a problem", "example": "Thanks for helping. No big deal, happy to do it."},
    {"term": "cut corners", "meaning": "to do something cheaply or carelessly", "example": "They saved money by cutting corners, and the quality dropped."},
    {"term": "crash", "meaning": "to sleep or stay somewhere temporarily", "example": "Can I crash on your couch after the concert?"},
    {"term": "flake out", "meaning": "to cancel plans or not follow through", "example": "Do not flake out on me at the last minute."},
    {"term": "wrap my head around", "meaning": "to understand something complicated", "example": "I am still trying to wrap my head around the new tax rules."},
    {"term": "rip off", "meaning": "to charge too much or cheat someone", "example": "That tourist trap restaurant is a total rip off."},
    {"term": "bail", "meaning": "to leave suddenly or cancel", "example": "He bailed on dinner because he was exhausted."},
    {"term": "go with the flow", "meaning": "to stay relaxed and accept changes", "example": "We do not have a full plan, so let us just go with the flow."},
    {"term": "shoot me a text", "meaning": "to send me a text message", "example": "Shoot me a text when you get home."},
    {"term": "in hot water", "meaning": "in trouble", "example": "He is in hot water with his boss after missing the deadline."},
    {"term": "call it a day", "meaning": "to stop working for now", "example": "We have done enough. Let us call it a day."},
    {"term": "back me up", "meaning": "to support what I say", "example": "Can you back me up in the meeting if this comes up?"},
    {"term": "my bad", "meaning": "it was my mistake", "example": "My bad, I sent the wrong file."},
    {"term": "the ball is in your court", "meaning": "it is your turn to act or decide", "example": "I sent the proposal yesterday, so now the ball is in your court."},
    {"term": "beat around the bush", "meaning": "to avoid saying something directly", "example": "Do not beat around the bush. Just tell me what happened."},
    {"term": "pull yourself together", "meaning": "to calm down and regain control", "example": "Take a breath and pull yourself together before the interview."},
    {"term": "fired up", "meaning": "excited and full of energy", "example": "The team was fired up after the coach's speech."},
    {"term": "down to earth", "meaning": "practical and easy to relate to", "example": "Even though she is famous, she is very down to earth."},
    {"term": "throw me a bone", "meaning": "to give a small favor or helpful sign", "example": "Throw me a bone and tell me whether I am close."},
    {"term": "take a pass", "meaning": "to decide not to join or accept", "example": "I am going to take a pass on dessert tonight."},
]
